-- Generated from src/utils/naceDatabase.ts
INSERT INTO public.nace_codes (nace_code, nace_title, hazard_class, sector)
VALUES
('05.10','Taş kömürü madenciliği','Çok Tehlikeli','mining'),
('05.20','Linyit madenciliği','Çok Tehlikeli','mining'),
('06.10','Ham petrol çıkarımı','Çok Tehlikeli','mining'),
('06.20','Doğal gaz çıkarımı','Çok Tehlikeli','mining'),
('07.10','Demir cevheri madenciliği','Çok Tehlikeli','mining'),
('07.21','Uranyum ve toryum cevheri madenciliği','Çok Tehlikeli','mining'),
('08.11','Süsleme ve yapı taşı, kireç taşı, alçı taşı, tebeşir ve kayağantaşı madenciliği','Çok Tehlikeli','mining'),
('08.12','Çakıl ve kum ocakları; kil ve kaolin çıkarımı','Çok Tehlikeli','mining'),
('08.91','Kimyasal ve gübreleme amaçlı maden madenciliği','Çok Tehlikeli','mining'),
('08.92','Turba çıkarımı','Çok Tehlikeli','mining'),
('08.93','Tuz çıkarımı','Çok Tehlikeli','mining'),
('09.10','Petrol ve doğal gaz çıkarımını destekleyici faaliyetler','Çok Tehlikeli','mining'),
('24.10','Ana demir ve çelik ürünleri ile ferro alaşımların imalatı','Çok Tehlikeli','manufacturing'),
('24.20','Çelik tüplerin, boruların, içi boş profillerin ve benzeri bağlantı parçalarının imalatı','Çok Tehlikeli','manufacturing'),
('24.31','Demirin ve çeliğin soğuk çekilmesi','Çok Tehlikeli','manufacturing'),
('24.32','Demirin ve çeliğin soğuk haddelenmesi','Çok Tehlikeli','manufacturing'),
('24.33','Demirin ve çeliğin soğuk şekillendirilmesi veya katlanması','Çok Tehlikeli','manufacturing'),
('24.41','Değerli metallerin üretimi','Çok Tehlikeli','manufacturing'),
('24.42','Alüminyum üretimi','Çok Tehlikeli','manufacturing'),
('24.43','Kurşun, çinko ve kalay üretimi','Çok Tehlikeli','manufacturing'),
('24.44','Bakır üretimi','Çok Tehlikeli','manufacturing'),
('24.45','Diğer demir dışı metallerin üretimi','Çok Tehlikeli','manufacturing'),
('24.51','Demir döküm','Çok Tehlikeli','manufacturing'),
('24.52','Çelik döküm','Çok Tehlikeli','manufacturing'),
('24.53','Hafif metaller döküm','Çok Tehlikeli','manufacturing'),
('24.54','Diğer demir dışı metallerin döküm','Çok Tehlikeli','manufacturing'),
('41.10','Bina inşaat projelerinin geliştirilmesi','Çok Tehlikeli','construction'),
('41.20','İkamet amaçlı olan veya olmayan binaların inşaatı','Çok Tehlikeli','construction'),
('42.11','Karayolları ve demiryollarının inşaatı','Çok Tehlikeli','construction'),
('42.12','Demiryolları ve metro hatlarının inşaatı','Çok Tehlikeli','construction'),
('42.13','Köprü ve tünel inşaatı','Çok Tehlikeli','construction'),
('42.21','Akışkan taşımaya yönelik hizmet projeleri inşaatı','Çok Tehlikeli','construction'),
('42.22','Elektrik ve telekomünikasyon hatlarının inşaatı','Çok Tehlikeli','construction'),
('42.91','Su projeleri inşaatı','Çok Tehlikeli','construction'),
('42.99','Başka yerde sınıflandırılmamış diğer bina dışı yapıların inşaatı','Çok Tehlikeli','construction'),
('43.11','Yıkım','Çok Tehlikeli','construction'),
('43.12','İnşaat sahası hazırlık faaliyetleri','Çok Tehlikeli','construction'),
('43.13','Test sondajı ve delme','Çok Tehlikeli','construction'),
('43.21','Elektrik tesisatı','Çok Tehlikeli','construction'),
('43.22','Sıhhi tesisat, ısıtma ve iklimlendirme tesisatı','Çok Tehlikeli','construction'),
('43.31','Sıvama (suvama) işleri','Çok Tehlikeli','construction'),
('43.32','Doğrama işleri','Çok Tehlikeli','construction'),
('43.33','Yer ve duvar kaplama','Çok Tehlikeli','construction'),
('43.34','Boya ve cam işleri','Çok Tehlikeli','construction'),
('43.99','Başka yerde sınıflandırılmamış diğer özel inşaat faaliyetleri','Çok Tehlikeli','construction'),
('49.10','Şehirlerarası demiryolu yolcu taşımacılığı','Çok Tehlikeli','transportation'),
('49.20','Demiryolu yük taşımacılığı','Çok Tehlikeli','transportation'),
('49.31','Kara taşımacılığıyla yapılan yolcu taşımacılığı','Çok Tehlikeli','transportation'),
('49.41','Karayolu yük taşımacılığı','Çok Tehlikeli','transportation'),
('50.10','Deniz ve kıyı sularında yolcu taşımacılığı','Çok Tehlikeli','transportation'),
('50.20','Deniz ve kıyı sularında yük taşımacılığı','Çok Tehlikeli','transportation'),
('51.10','Havayolu ile yolcu taşımacılığı','Çok Tehlikeli','transportation'),
('51.21','Havayolu ile yük taşımacılığı','Çok Tehlikeli','transportation'),
('20.11','Sanayi gazları imalatı','Çok Tehlikeli','manufacturing'),
('20.12','Boya maddeleri imalatı','Çok Tehlikeli','manufacturing'),
('20.13','Diğer inorganik temel kimyasal maddelerin imalatı','Çok Tehlikeli','manufacturing'),
('20.14','Diğer organik temel kimyasal maddelerin imalatı','Çok Tehlikeli','manufacturing'),
('20.15','Gübre ve azot bileşikleri imalatı','Çok Tehlikeli','manufacturing'),
('20.16','Birincil formda plastik hammaddeleri imalatı','Çok Tehlikeli','manufacturing'),
('20.17','Birincil formda sentetik kauçuk imalatı','Çok Tehlikeli','manufacturing'),
('20.20','Haşere ilaçları ve diğer zirai-kimyasal ürünlerin imalatı','Çok Tehlikeli','manufacturing'),
('20.30','Boya, vernik ve benzeri kaplayıcı maddeler ile matbaa mürekkebi ve macun imalatı','Çok Tehlikeli','manufacturing'),
('10.11','Et işleme ve saklaması','Tehlikeli','manufacturing'),
('10.12','Kanatlı hayvan eti işleme ve saklaması','Tehlikeli','manufacturing'),
('10.13','Et ve kanatlı hayvan etinden üretilen et ürünleri imalatı','Tehlikeli','manufacturing'),
('10.20','Balık, kabuklu deniz hayvanları ve yumuşakçaların işlenmesi ve saklanması','Tehlikeli','manufacturing'),
('10.31','Patatesin işlenmesi ve saklanması','Tehlikeli','manufacturing'),
('10.32','Meyve ve sebze suyu imalatı','Tehlikeli','manufacturing'),
('10.39','Meyve ve sebzelerin işlenmesi ve saklanması (dondurulmuş olanlar hariç)','Tehlikeli','manufacturing'),
('10.41','Sıvı ve katı yağ imalatı','Tehlikeli','manufacturing'),
('10.42','Margarin ve benzeri yenilebilir katı yağların imalatı','Tehlikeli','manufacturing'),
('10.51','Süt işleme ve peynir imalatı','Tehlikeli','manufacturing'),
('10.52','Dondurma imalatı','Tehlikeli','manufacturing'),
('10.61','Öğütülmüş tahıl ürünleri imalatı','Tehlikeli','manufacturing'),
('10.62','Nişasta ve nişastalı ürünlerin imalatı','Tehlikeli','manufacturing'),
('10.71','Ekmek imalatı; taze pastane ürünleri ve taze kek imalatı','Tehlikeli','manufacturing'),
('10.72','Peksimet ve bisküvi imalatı; dayanıklı pastane ürünleri ve dayanıklı kek imalatı','Tehlikeli','manufacturing'),
('10.73','Makarna, şehriye, kuskus ve benzeri mamul ürünlerin imalatı','Tehlikeli','manufacturing'),
('10.81','Şeker imalatı','Tehlikeli','manufacturing'),
('10.82','Kakao, çikolata ve şekerleme imalatı','Tehlikeli','manufacturing'),
('10.83','Çay ve kahve işleme','Tehlikeli','manufacturing'),
('10.84','Baharat, sos, sirke ve diğer çeşni maddeleri imalatı','Tehlikeli','manufacturing'),
('10.85','Hazır yemeklerin imalatı','Tehlikeli','manufacturing'),
('10.86','Homojenize gıda müstahzarları ve diyet gıdaların imalatı','Tehlikeli','manufacturing'),
('10.89','Başka yerde sınıflandırılmamış diğer gıda maddelerinin imalatı','Tehlikeli','manufacturing'),
('10.91','Hazır hayvan yemleri imalatı','Tehlikeli','manufacturing'),
('10.92','Ev hayvanları için hazır gıda imalatı','Tehlikeli','manufacturing'),
('11.01','Alkollü içeceklerin damıtılması, arıtılması ve harmanlanması','Tehlikeli','manufacturing'),
('11.02','Üzümden şarap imalatı','Tehlikeli','manufacturing'),
('11.03','Elma şarabı ve diğer meyvalardan şarap imalatı','Tehlikeli','manufacturing'),
('11.04','Diğer damıtılmamış mayalı içeceklerin imalatı','Tehlikeli','manufacturing'),
('11.05','Bira imalatı','Tehlikeli','manufacturing'),
('11.06','Malt imalatı','Tehlikeli','manufacturing'),
('11.07','Alkolsüz içeceklerin imalatı; maden suları ve diğer şişelenmiş suların üretimi','Tehlikeli','manufacturing'),
('13.10','Tekstil elyafının hazırlanması ve bükülmesi','Tehlikeli','manufacturing'),
('13.20','Dokuma','Tehlikeli','manufacturing'),
('13.30','Tekstil ürünlerinin bitirilmesi','Tehlikeli','manufacturing'),
('13.91','Örme ve tığ işi kumaşların imalatı','Tehlikeli','manufacturing'),
('13.92','Hazır tekstil eşyalarının imalatı (giyim eşyası hariç)','Tehlikeli','manufacturing'),
('13.93','Halı ve kilim imalatı','Tehlikeli','manufacturing'),
('13.94','Sicim, ip, urgan ve ağ imalatı','Tehlikeli','manufacturing'),
('13.95','Dokumaya elverişsiz tekstiller ve bunlardan mamul eşya imalatı','Tehlikeli','manufacturing'),
('13.96','Diğer teknik ve sınai tekstiller imalatı','Tehlikeli','manufacturing'),
('13.99','Başka yerde sınıflandırılmamış diğer tekstil ürünlerinin imalatı','Tehlikeli','manufacturing'),
('14.11','Deri giyim eşyası imalatı','Tehlikeli','manufacturing'),
('14.12','İş giysisi imalatı','Tehlikeli','manufacturing'),
('14.13','Diğer dış giyim eşyaları imalatı','Tehlikeli','manufacturing'),
('14.14','İç giyim eşyası imalatı','Tehlikeli','manufacturing'),
('14.19','Diğer giyim eşyaları ve giysi aksesuarlarının imalatı','Tehlikeli','manufacturing'),
('14.20','Kürkten eşya imalatı','Tehlikeli','manufacturing'),
('14.31','Örme ve tığ işi çorap imalatı','Tehlikeli','manufacturing'),
('14.39','Diğer örme ve tığ işi giyim eşyası imalatı','Tehlikeli','manufacturing'),
('15.11','Derinin tabaklanması ve işlenmesi; kürkün işlenmesi ve boyanması','Tehlikeli','manufacturing'),
('15.12','Bavul, el çantası ve benzeri eşyaların, saraç ve semer eşyalarının imalatı','Tehlikeli','manufacturing'),
('15.20','Ayakkabı, bot, terlik vb. imalatı','Tehlikeli','manufacturing'),
('16.10','Ağaç, ağaç ve mantar ürünlerinin biçilmesi, planyalanması ve emprenye edilmesi','Tehlikeli','manufacturing'),
('16.21','Tahta kaplama paneli ve ağaç esaslı diğer panel imalatı','Tehlikeli','manufacturing'),
('16.22','Birleştirilmiş parke yer döşemesi imalatı','Tehlikeli','manufacturing'),
('16.23','Marangoz ve doğrama ürünlerinin imalatı','Tehlikeli','manufacturing'),
('16.24','Ahşap konteyner imalatı','Tehlikeli','manufacturing'),
('16.29','Diğer ağaç ürünleri imalatı; saz, saman ve benzeri malzemelerden örülerek eşya imalatı','Tehlikeli','manufacturing'),
('17.11','Kağıt hamuru imalatı','Tehlikeli','manufacturing'),
('17.12','Kağıt ve karton imalatı','Tehlikeli','manufacturing'),
('17.21','Oluklu kağıt ve karton imalatı ile kağıt ve kartondan yapılan muhafazaların imalatı','Tehlikeli','manufacturing'),
('17.22','Evde ve sıhhı amaçlarla kullanılan kağıt ürünlerinin imalatı','Tehlikeli','manufacturing'),
('17.23','Kağıt kırtasiye ürünlerinin imalatı','Tehlikeli','manufacturing'),
('17.24','Duvar kağıdı imalatı','Tehlikeli','manufacturing'),
('17.29','Kağıt ve kartondan diğer ürünlerin imalatı','Tehlikeli','manufacturing'),
('18.11','Gazete basımı','Tehlikeli','manufacturing'),
('18.12','Diğer matbaa işleri','Tehlikeli','manufacturing'),
('18.13','Basım ve yayım öncesi hizmetler','Tehlikeli','manufacturing'),
('18.14','Ciltçilik ve ilgili hizmetler','Tehlikeli','manufacturing'),
('18.20','Kayıtlı medyanın çoğaltılması','Tehlikeli','manufacturing'),
('19.10','Kok fırını ürünleri imalatı','Tehlikeli','manufacturing'),
('19.20','Rafine edilmiş petrol ürünleri imalatı','Tehlikeli','manufacturing'),
('21.10','Temel eczacılık ürünleri imalatı','Tehlikeli','manufacturing'),
('21.20','İlaç ve eczacılığa ilişkin diğer ürünlerin imalatı','Tehlikeli','manufacturing'),
('22.11','Kauçuk lastik ve iç lastik imalatı; lastiğin protez edilmesi ve yenilenmesi','Tehlikeli','manufacturing'),
('22.19','Diğer kauçuk ürünlerinin imalatı','Tehlikeli','manufacturing'),
('22.21','Plastik tabaka, levha, tüp ve profil imalatı','Tehlikeli','manufacturing'),
('22.22','Plastik torba, çanta, poşet, çuval, kutu, damacana, şişe, makara vb. paketleme malzemelerinin imalatı','Tehlikeli','manufacturing'),
('22.23','Plastik inşaat malzemesi imalatı','Tehlikeli','manufacturing'),
('22.29','Diğer plastik ürünlerin imalatı','Tehlikeli','manufacturing'),
('23.11','Düz cam imalatı','Tehlikeli','manufacturing'),
('23.12','Düz camın şekillendirilmesi ve işlenmesi','Tehlikeli','manufacturing'),
('23.13','İçi boş cam imalatı','Tehlikeli','manufacturing'),
('23.14','Cam elyafı imalatı','Tehlikeli','manufacturing'),
('23.19','Diğer camların imalatı (teknik amaçlı camlar dahil) ile işlenmesi','Tehlikeli','manufacturing'),
('23.20','Ateşe dayanıklı (refrakter) ürünlerin imalatı','Tehlikeli','manufacturing'),
('23.31','Seramik karo ve kaldırım taşları imalatı','Tehlikeli','manufacturing'),
('23.32','Pişmiş kilden tuğla, kiremit ve inşaat malzemeleri imalatı','Tehlikeli','manufacturing'),
('23.41','Seramik ev ve süs eşyası imalatı','Tehlikeli','manufacturing'),
('23.42','Seramik sıhhi ürünlerin imalatı','Tehlikeli','manufacturing'),
('23.43','Seramik yalıtkanlar ve yalıtkanlık malzemeleri imalatı','Tehlikeli','manufacturing'),
('23.44','Diğer teknik seramik ürünlerin imalatı','Tehlikeli','manufacturing'),
('23.49','Diğer seramik ürünlerin imalatı','Tehlikeli','manufacturing'),
('23.51','Çimento imalatı','Tehlikeli','manufacturing'),
('23.52','Kireç ve alçı imalatı','Tehlikeli','manufacturing'),
('23.61','İnşaatlarda kullanılmak üzere beton ürünlerin imalatı','Tehlikeli','manufacturing'),
('23.62','İnşaatlarda kullanılmak üzere alçı ürünlerin imalatı','Tehlikeli','manufacturing'),
('23.63','Hazır beton imalatı','Tehlikeli','manufacturing'),
('23.64','Harç imalatı','Tehlikeli','manufacturing'),
('23.65','Lifli çimento imalatı','Tehlikeli','manufacturing'),
('23.69','Beton, çimento ve alçıdan diğer ürünlerin imalatı','Tehlikeli','manufacturing'),
('23.70','Taş yontma, biçme, şekillendirme ve bitirme işleri','Tehlikeli','manufacturing'),
('23.91','Aşındırıcı ürünlerin imalatı','Tehlikeli','manufacturing'),
('23.99','Başka yerde sınıflandırılmamış metalik olmayan diğer mineral ürünlerin imalatı','Tehlikeli','manufacturing'),
('25.11','Metal yapı ve metal yapı parçalarının imalatı','Tehlikeli','manufacturing'),
('25.12','Metal kapı ve pencere imalatı','Tehlikeli','manufacturing'),
('25.21','Merkezi ısıtma radyatörleri ve kazanların imalatı','Tehlikeli','manufacturing'),
('25.29','Diğer metal sarnıç, rezervuar ve konteyner imalatı','Tehlikeli','manufacturing'),
('25.30','Buhar jeneratörü imalatı (merkezi ısıtma için sıcak su kazanları hariç)','Tehlikeli','manufacturing'),
('25.40','Silah ve mühimmat imalatı','Tehlikeli','manufacturing'),
('25.50','Metallerin dövülmesi, preslenmesi, baskılanması ve yuvarlanması; toz metalurjisi','Tehlikeli','manufacturing'),
('25.61','Metallerin kaplanması ve kaplamaları','Tehlikeli','manufacturing'),
('25.62','Metallerin işlenmesi ve kaplanması','Tehlikeli','manufacturing'),
('25.71','Çatal bıçak takımı imalatı','Tehlikeli','manufacturing'),
('25.72','Kilit ve menteşe imalatı','Tehlikeli','manufacturing'),
('25.73','El aletleri imalatı','Tehlikeli','manufacturing'),
('25.91','Çelik varil ve benzeri kapların imalatı','Tehlikeli','manufacturing'),
('25.92','Metalden hafif paketleme malzemelerinin imalatı','Tehlikeli','manufacturing'),
('25.93','Tel ürünleri, zincir ve yay imalatı','Tehlikeli','manufacturing'),
('25.94','Bağlantı elemanları ve vida makine ürünleri imalatı','Tehlikeli','manufacturing'),
('25.99','Başka yerde sınıflandırılmamış diğer metal ürünlerinin imalatı','Tehlikeli','manufacturing'),
('26.11','Elektronik bileşenlerin imalatı','Tehlikeli','manufacturing'),
('26.12','Yüklü elektronik kartların imalatı','Tehlikeli','manufacturing'),
('26.20','Bilgisayarlar ve bilgisayar çevre birimleri imalatı','Tehlikeli','manufacturing'),
('26.30','İletişim teçhizatı imalatı','Tehlikeli','manufacturing'),
('26.40','Tüketici elektroniği ürünlerinin imalatı','Tehlikeli','manufacturing'),
('26.51','Ölçü, test ve seyrüsefer amaçlı alet ve cihazların imalatı','Tehlikeli','manufacturing'),
('26.52','Saat imalatı','Tehlikeli','manufacturing'),
('26.60','Işınlama, elektro medikal ve elektro terapi cihazlarının imalatı','Tehlikeli','manufacturing'),
('26.70','Optik aletler ve fotografik ekipman imalatı','Tehlikeli','manufacturing'),
('26.80','Manyetik ve optik ortamların imalatı','Tehlikeli','manufacturing'),
('27.11','Elektrik motoru, jeneratör ve transformatör imalatı','Tehlikeli','manufacturing'),
('27.12','Elektrik dağıtım ve kontrol cihazları imalatı','Tehlikeli','manufacturing'),
('27.20','Pil ve akümülatör imalatı','Tehlikeli','manufacturing'),
('27.31','Fiber optik kablolar imalatı','Tehlikeli','manufacturing'),
('27.32','Diğer elektronik ve elektrik telleri ve kabloların imalatı','Tehlikeli','manufacturing'),
('27.33','Kablo tesisatı cihazları imalatı','Tehlikeli','manufacturing'),
('27.40','Elektrikli aydınlatma ekipmanları imalatı','Tehlikeli','manufacturing'),
('27.51','Elektrikli ev aletlerinin imalatı','Tehlikeli','manufacturing'),
('27.52','Elektrikli olmayan ev aletlerinin imalatı','Tehlikeli','manufacturing'),
('27.90','Diğer elektrikli ekipmanların imalatı','Tehlikeli','manufacturing'),
('28.11','Motor ve türbinlerin imalatı (uçak, motorlu taşıt ve motosiklet motorları hariç)','Tehlikeli','manufacturing'),
('28.12','Akışkan gücü ile çalışan ekipmanların imalatı','Tehlikeli','manufacturing'),
('28.13','Diğer pompa ve kompresörlerin imalatı','Tehlikeli','manufacturing'),
('28.14','Diğer musluk ve vana imalatı','Tehlikeli','manufacturing'),
('28.15','Rulmanlar, dişli takımları, şanzıman donanımları imalatı','Tehlikeli','manufacturing'),
('28.21','Fırınlar, ocaklar ve brülörler imalatı','Tehlikeli','manufacturing'),
('28.22','Kaldırma ve taşıma ekipmanları imalatı','Tehlikeli','manufacturing'),
('28.23','Büro makineleri ve ekipmanları imalatı (bilgisayarlar ve çevre birimleri hariç)','Tehlikeli','manufacturing'),
('28.24','Motorlu el aletlerinin imalatı','Tehlikeli','manufacturing'),
('28.25','Endüstriyel soğutma ve havalandırma ekipmanlarının imalatı','Tehlikeli','manufacturing'),
('28.29','Başka yerde sınıflandırılmamış diğer genel amaçlı makinelerin imalatı','Tehlikeli','manufacturing'),
('28.30','Tarım ve ormancılık makinelerinin imalatı','Tehlikeli','manufacturing'),
('28.41','Metal işleme makinelerinin imalatı','Tehlikeli','manufacturing'),
('28.49','Diğer takım tezgahlarının imalatı','Tehlikeli','manufacturing'),
('28.91','Metalurji makinelerinin imalatı','Tehlikeli','manufacturing'),
('28.92','Maden, taş ocağı ve inşaat makinelerinin imalatı','Tehlikeli','manufacturing'),
('28.93','Gıda, içecek ve tütün işleme makinelerinin imalatı','Tehlikeli','manufacturing'),
('28.94','Tekstil, giyim eşyası ve deri üretimi için makinelerin imalatı','Tehlikeli','manufacturing'),
('28.95','Kağıt ve karton üretimi için makinelerin imalatı','Tehlikeli','manufacturing'),
('28.96','Plastik ve kauçuk makinelerinin imalatı','Tehlikeli','manufacturing'),
('28.99','Başka yerde sınıflandırılmamış özel amaçlı diğer makinelerin imalatı','Tehlikeli','manufacturing'),
('29.10','Motorlu kara taşıtı imalatı','Tehlikeli','manufacturing'),
('29.20','Motorlu kara taşıtları için karoseri imalatı; treyler (römork) ve yarı treyler (yarı römork) imalatı','Tehlikeli','manufacturing'),
('29.31','Motorlu kara taşıtları için elektrik ve elektronik donanımların imalatı','Tehlikeli','manufacturing'),
('29.32','Motorlu kara taşıtları için diğer parça ve aksesuarların imalatı','Tehlikeli','manufacturing'),
('30.11','Gemi ve yüzer yapıların inşaası','Tehlikeli','manufacturing'),
('30.12','Eğlence ve spor amaçlı teknelerin inşaası','Tehlikeli','manufacturing'),
('30.20','Demiryolu lokomotifleri ve vagonlarının imalatı','Tehlikeli','manufacturing'),
('30.30','Hava ve uzay araçları ile ilgili makinelerin imalatı','Tehlikeli','manufacturing'),
('30.40','Askeri savaş araçlarının imalatı','Tehlikeli','manufacturing'),
('30.91','Motosiklet imalatı','Tehlikeli','manufacturing'),
('30.92','Bisiklet ve özürlü aracı imalatı','Tehlikeli','manufacturing'),
('30.99','Başka yerde sınıflandırılmamış diğer ulaşım ekipmanlarının imalatı','Tehlikeli','manufacturing'),
('31.01','Büro ve mağaza mobilyaları imalatı','Tehlikeli','manufacturing'),
('31.02','Mutfak mobilyası imalatı','Tehlikeli','manufacturing'),
('31.03','Yatak imalatı','Tehlikeli','manufacturing'),
('31.09','Diğer mobilyaların imalatı','Tehlikeli','manufacturing'),
('32.11','Madeni para basımı','Tehlikeli','manufacturing'),
('32.12','Kuyumculuk ve ilgili eşya imalatı','Tehlikeli','manufacturing'),
('32.13','Takı eşyası ve benzeri eşya imalatı','Tehlikeli','manufacturing'),
('32.20','Müzik aletlerinin imalatı','Tehlikeli','manufacturing'),
('32.30','Spor malzemeleri imalatı','Tehlikeli','manufacturing'),
('32.40','Oyun ve oyuncak imalatı','Tehlikeli','manufacturing'),
('32.50','Tıbbi ve dişçilik ile ilgili araç ve gereçlerin imalatı','Tehlikeli','manufacturing'),
('32.91','Süpürge ve fırça imalatı','Tehlikeli','manufacturing'),
('32.99','Başka yerde sınıflandırılmamış diğer imalatlar','Tehlikeli','manufacturing'),
('33.11','Metal ürünlerin onarımı','Tehlikeli','manufacturing'),
('33.12','Makinelerin onarımı','Tehlikeli','manufacturing'),
('33.13','Elektronik ve optik ekipmanların onarımı','Tehlikeli','manufacturing'),
('33.14','Elektrikli ekipmanların onarımı','Tehlikeli','manufacturing'),
('33.15','Gemilerin ve teknelerin onarımı ve bakımı','Tehlikeli','manufacturing'),
('33.16','Hava ve uzay araçlarının onarımı ve bakımı','Tehlikeli','manufacturing'),
('33.17','Diğer ulaşım ekipmanlarının onarımı ve bakımı','Tehlikeli','manufacturing'),
('33.19','Diğer ekipmanların onarımı','Tehlikeli','manufacturing'),
('33.20','Sanayi makine ve ekipmanlarının kurulumu','Tehlikeli','manufacturing'),
('35.11','Elektrik enerjisinin üretimi','Tehlikeli','energy'),
('35.12','Elektrik enerjisinin iletimi','Tehlikeli','energy'),
('35.13','Elektrik enerjisinin dağıtımı','Tehlikeli','energy'),
('35.14','Elektrik enerjisinin ticareti','Tehlikeli','energy'),
('35.21','Gaz yakıtların imalatı','Tehlikeli','energy'),
('35.22','Boru hattı ile gaz yakıt dağıtımı','Tehlikeli','energy'),
('35.23','Gaz yakıtların ticareti','Tehlikeli','energy'),
('35.30','Buhar ve iklimlendirme temini','Tehlikeli','energy'),
('36.00','Suyun toplanması, arıtılması ve dağıtılması','Tehlikeli','utilities'),
('37.00','Kanalizasyon','Tehlikeli','utilities'),
('38.11','Tehlikesiz atıkların toplanması','Tehlikeli','waste'),
('38.12','Tehlikeli atıkların toplanması','Tehlikeli','waste'),
('38.21','Tehlikesiz atıkların ıslahı ve bertarafı','Tehlikeli','waste'),
('38.22','Tehlikeli atıkların ıslahı ve bertarafı','Tehlikeli','waste'),
('38.31','Hurdaların parçalara ayrılması','Tehlikeli','waste'),
('38.32','Tasnif edilmiş materyallerin geri kazanımı','Tehlikeli','waste'),
('39.00','İyileştirme faaliyetleri ve diğer atık yönetimi hizmetleri','Tehlikeli','utilities'),
('46.21','Tahıllar, işlenmemiş tütün, tohumlar ve hayvan yemleri toptan ticareti','Tehlikeli','logistics'),
('46.75','Kimyasal ürünlerin toptan ticareti','Tehlikeli','logistics'),
('49.32','Taksi işletmeciliği','Tehlikeli','transportation'),
('49.39','Başka yerde sınıflandırılmamış diğer kara yolu taşımacılığı','Tehlikeli','transportation'),
('49.42','Evden eve taşımacılık hizmetleri','Tehlikeli','transportation'),
('49.50','Boru hattı taşımacılığı','Tehlikeli','transportation'),
('52.10','Depolama ve ambarcılık','Tehlikeli','logistics'),
('52.21','Kara taşımacılığına yardımcı hizmet faaliyetleri','Tehlikeli','logistics'),
('52.22','Su yolu taşımacılığına yardımcı hizmet faaliyetleri','Tehlikeli','logistics'),
('52.23','Hava yolu taşımacılığına yardımcı hizmet faaliyetleri','Tehlikeli','logistics'),
('52.24','Kargo yükleme boşaltma hizmetleri','Tehlikeli','logistics'),
('52.29','Taşımacılığa yardımcı diğer faaliyetler','Tehlikeli','logistics'),
('45.11','Motorlu kara taşıtlarının ticareti (satış)','Az Tehlikeli','office'),
('45.19','Diğer motorlu kara taşıtlarının ticareti (satış)','Az Tehlikeli','office'),
('45.20','Motorlu kara taşıtlarının bakım ve onarımı','Az Tehlikeli','office'),
('45.31','Motorlu kara taşıtı parçalarının ve aksesuarlarının toptan ticareti','Az Tehlikeli','office'),
('45.32','Motorlu kara taşıtı parçalarının ve aksesuarlarının perakende ticareti','Az Tehlikeli','office'),
('45.40','Motosiklet, motosiklet parçaları ve aksesuarlarının satışı, bakımı ve onarımı','Az Tehlikeli','office'),
('46.11','Tarımsal hammadde, canlı hayvan, tekstil hammaddesi ve yarı mamul ürünlerinin ticaretinde aracılık','Az Tehlikeli','office'),
('46.12','Yakıtların, madenlerin, metallerin ve sanayi kimyasallarının ticaretinde aracılık','Az Tehlikeli','office'),
('46.13','Kereste ve inşaat malzemelerinin ticaretinde aracılık','Az Tehlikeli','office'),
('46.14','Makine, sanayi ekipmanı, gemi ve uçakların ticaretinde aracılık','Az Tehlikeli','office'),
('46.15','Mobilya, ev eşyası, hırdavat ve nalburiye ürünlerinin ticaretinde aracılık','Az Tehlikeli','office'),
('46.16','Tekstil ürünleri, hazır giyim, kürk, ayakkabı ve deri eşyaların ticaretinde aracılık','Az Tehlikeli','office'),
('46.17','Gıda, içecek ve tütün ticaretinde aracılık','Az Tehlikeli','office'),
('46.18','Belirli bir mala tahsis edilmiş diğer uzmanlaşmış aracılar','Az Tehlikeli','office'),
('46.19','Çeşitli malların ticaretinde aracılık','Az Tehlikeli','office'),
('47.11','Gıda ürünleri, içecek ve tütün satışının yapıldığı perakende mağazalar','Az Tehlikeli','retail'),
('47.19','Diğer perakende mağazalar','Az Tehlikeli','retail'),
('47.21','Meyve ve sebze perakende ticareti','Az Tehlikeli','retail'),
('47.22','Et ve et ürünleri perakende ticareti','Az Tehlikeli','retail'),
('47.23','Balık, kabuklu deniz hayvanları ve yumuşakçalar perakende ticareti','Az Tehlikeli','retail'),
('47.24','Ekmek, hamur işleri ve şekerlemeler perakende ticareti','Az Tehlikeli','retail'),
('47.25','İçeceklerin perakende ticareti','Az Tehlikeli','retail'),
('47.26','Tütün mamullerinin perakende ticareti','Az Tehlikeli','retail'),
('47.29','Diğer gıda ürünleri perakende ticareti','Az Tehlikeli','retail'),
('47.30','Motorlu taşıt yakıtının perakende ticareti','Az Tehlikeli','retail'),
('47.41','Bilgisayar, çevre birimleri ve yazılım perakende ticareti','Az Tehlikeli','retail'),
('47.42','Telekomünikasyon ekipmanlarının perakende ticareti','Az Tehlikeli','retail'),
('47.43','Sesli ve görüntülü ekipmanların perakende ticareti','Az Tehlikeli','retail'),
('47.51','Tekstil ürünleri perakende ticareti','Az Tehlikeli','retail'),
('47.52','Nalburiye, boya ve cam eşyaların perakende ticareti','Az Tehlikeli','retail'),
('47.53','Halı, kilim, duvar ve yer kaplamaları perakende ticareti','Az Tehlikeli','retail'),
('47.54','Elektrikli ev aletlerinin perakende ticareti','Az Tehlikeli','retail'),
('47.59','Mobilya, aydınlatma ekipmanı ve diğer ev eşyalarının perakende ticareti','Az Tehlikeli','retail'),
('47.61','Kitap perakende ticareti','Az Tehlikeli','retail'),
('47.62','Gazete ve kırtasiye perakende ticareti','Az Tehlikeli','retail'),
('47.63','Müzik ve video kasetleri perakende ticareti','Az Tehlikeli','retail'),
('47.64','Spor ekipmanları perakende ticareti','Az Tehlikeli','retail'),
('47.65','Oyun ve oyuncak perakende ticareti','Az Tehlikeli','retail'),
('47.71','Giyim eşyası perakende ticareti','Az Tehlikeli','retail'),
('47.72','Ayakkabı ve deri eşyaların perakende ticareti','Az Tehlikeli','retail'),
('47.73','Eczacılık ürünleri perakende ticareti','Az Tehlikeli','retail'),
('47.74','Tıbbi ürünler, ortopedik ürünler ve eczacılık ürünleri perakende ticareti','Az Tehlikeli','retail'),
('47.75','Kozmetik ve kişisel bakım ürünlerinin perakende ticareti','Az Tehlikeli','retail'),
('47.76','Çiçek, bitki, tohum, gübre, ev hayvanı ve ev hayvanı yemi perakende ticareti','Az Tehlikeli','retail'),
('47.77','Saat, mücevherat ve takı eşyası perakende ticareti','Az Tehlikeli','retail'),
('47.78','Diğer yeni ürünlerin perakende ticareti','Az Tehlikeli','retail'),
('47.79','İkinci el eşyaların perakende ticareti','Az Tehlikeli','retail'),
('47.81','Tezgah ve pazarlarda gıda, içecek ve tütün ürünleri perakende ticareti','Az Tehlikeli','retail'),
('47.82','Tezgah ve pazarlarda tekstil, hazır giyim ve ayakkabı perakende ticareti','Az Tehlikeli','retail'),
('47.89','Tezgah ve pazarlarda diğer ürünlerin perakende ticareti','Az Tehlikeli','retail'),
('47.91','Posta yoluyla veya internet üzerinden perakende ticaret','Az Tehlikeli','retail'),
('47.99','Mağaza, tezgah ve pazar dışı perakende ticaret','Az Tehlikeli','retail'),
('55.10','Oteller ve benzeri konaklama yerleri','Az Tehlikeli','hospitality'),
('55.20','Tatil ve diğer kısa süreli konaklama yerleri','Az Tehlikeli','hospitality'),
('55.30','Kamp alanları, motorlu karavan ve çekme karavan için yerler','Az Tehlikeli','hospitality'),
('55.90','Diğer konaklama yerleri','Az Tehlikeli','hospitality'),
('56.10','Lokantalar ve seyyar yemek hizmeti faaliyetleri','Az Tehlikeli','hospitality'),
('56.21','Özel günlerde yapılan yemek hizmeti faaliyetleri','Az Tehlikeli','hospitality'),
('56.29','Diğer yemek hizmeti faaliyetleri','Az Tehlikeli','hospitality'),
('56.30','İçecek sunum faaliyetleri','Az Tehlikeli','hospitality'),
('58.11','Kitap yayımı','Az Tehlikeli','office'),
('58.12','Rehber, adres ve posta listesi yayımı','Az Tehlikeli','office'),
('58.13','Gazete yayımı','Az Tehlikeli','office'),
('58.14','Dergi ve süreli yayınların yayımı','Az Tehlikeli','office'),
('58.19','Diğer yayımcılık faaliyetleri','Az Tehlikeli','office'),
('58.21','Bilgisayar oyunlarının yayımlanması','Az Tehlikeli','office'),
('58.29','Diğer yazılım programlarının yayımlanması','Az Tehlikeli','office'),
('59.11','Sinema filmi, video ve televizyon programları yapımcılığı faaliyetleri','Az Tehlikeli','office'),
('59.12','Sinema filmi, video ve televizyon programlarının yapım sonrası faaliyetleri','Az Tehlikeli','office'),
('59.13','Sinema filmi, video ve televizyon programlarının dağıtım faaliyetleri','Az Tehlikeli','office'),
('59.14','Sinema filmi gösterim faaliyetleri','Az Tehlikeli','office'),
('59.20','Ses kaydı ve müzik yayımlama faaliyetleri','Az Tehlikeli','office'),
('60.10','Radyo yayıncılığı','Az Tehlikeli','office'),
('60.20','Televizyon yayıncılığı ve programlanması faaliyetleri','Az Tehlikeli','office'),
('61.10','Kablolu telekomünikasyon faaliyetleri','Az Tehlikeli','office'),
('61.20','Kablosuz telekomünikasyon faaliyetleri','Az Tehlikeli','office'),
('61.30','Uydu üzerinden telekomünikasyon faaliyetleri','Az Tehlikeli','office'),
('61.90','Diğer telekomünikasyon faaliyetleri','Az Tehlikeli','office'),
('62.01','Bilgisayar programlama faaliyetleri','Az Tehlikeli','office'),
('62.02','Bilgisayar danışmanlık faaliyetleri','Az Tehlikeli','office'),
('62.03','Bilgisayar tesisleri yönetim faaliyetleri','Az Tehlikeli','office'),
('62.09','Diğer bilgi teknolojileri ve bilgisayar hizmet faaliyetleri','Az Tehlikeli','office'),
('63.11','Veri işleme, barındırma (hosting) ve ilgili faaliyetler','Az Tehlikeli','office'),
('63.12','Web portalları','Az Tehlikeli','office'),
('63.91','Haber ajanslarının faaliyetleri','Az Tehlikeli','office'),
('63.99','Başka yerde sınıflandırılmamış diğer bilgi hizmet faaliyetleri','Az Tehlikeli','office'),
('64.11','Merkez bankacılığı','Az Tehlikeli','office'),
('64.19','Diğer parasal aracılık','Az Tehlikeli','office'),
('64.20','Holding şirketlerinin faaliyetleri','Az Tehlikeli','office'),
('64.30','Tröstler, fonlar ve benzeri finansal varlıklar','Az Tehlikeli','office'),
('64.91','Finansal kiralama (leasing)','Az Tehlikeli','office'),
('64.92','Diğer kredi verme','Az Tehlikeli','office'),
('64.99','Sigorta ve emeklilik fonları hariç, başka yerde sınıflandırılmamış diğer finansal hizmet faaliyetleri','Az Tehlikeli','office'),
('65.11','Hayat sigortası','Az Tehlikeli','office'),
('65.12','Hayat dışı sigortalar','Az Tehlikeli','office'),
('65.20','Reasürans','Az Tehlikeli','office'),
('65.30','Emeklilik fonları','Az Tehlikeli','office'),
('66.11','Finansal piyasa yönetimi','Az Tehlikeli','office'),
('66.12','Menkul kıymetler ve emtia sözleşmeleri aracılığı','Az Tehlikeli','office'),
('66.19','Finansal hizmetler için diğer yardımcı faaliyetler','Az Tehlikeli','office'),
('66.21','Risk ve hasar değerlendirme','Az Tehlikeli','office'),
('66.22','Sigorta acentelerinin ve sigorta brokerlarının faaliyetleri','Az Tehlikeli','office'),
('66.29','Sigorta ve emeklilik fonları için diğer yardımcı faaliyetler','Az Tehlikeli','office'),
('66.30','Fon yönetimi faaliyetleri','Az Tehlikeli','office'),
('68.10','Kendi mülkünün alınıp satılması','Az Tehlikeli','real_estate'),
('68.20','Kendi binası veya kiraladığı gayrimenkulün kiralanması ve işletilmesi','Az Tehlikeli','real_estate'),
('68.31','Gayrimenkul acentelerinin faaliyetleri','Az Tehlikeli','real_estate'),
('68.32','Ücret veya sözleşmeye dayalı olarak, gayrimenkullerin yönetimi','Az Tehlikeli','real_estate'),
('69.10','Hukuk faaliyetleri','Az Tehlikeli','office'),
('69.20','Muhasebe, defter tutma ve denetim faaliyetleri; vergi danışmanlığı','Az Tehlikeli','office'),
('70.10','İdare faaliyetleri','Az Tehlikeli','office'),
('70.21','Halkla ilişkiler ve iletişim faaliyetleri','Az Tehlikeli','office'),
('70.22','İşletme ve diğer idari danışmanlık faaliyetleri','Az Tehlikeli','office'),
('71.11','Mimarlık faaliyetleri','Az Tehlikeli','office'),
('71.12','Mühendislik faaliyetleri ve ilgili teknik danışmanlık','Az Tehlikeli','office'),
('71.20','Teknik test ve analiz faaliyetleri','Az Tehlikeli','office'),
('72.11','Biyoteknoloji alanında araştırma ve deneysel geliştirme faaliyetleri','Az Tehlikeli','office'),
('72.19','Doğa bilimleri ve mühendislik alanında diğer araştırma ve deneysel geliştirme faaliyetleri','Az Tehlikeli','office'),
('72.20','Sosyal bilimler ve beşeri bilimler alanında araştırma ve deneysel geliştirme faaliyetleri','Az Tehlikeli','office'),
('73.11','Reklam ajanslarının faaliyetleri','Az Tehlikeli','office'),
('73.12','Medyada reklam ve gösterim hizmetleri','Az Tehlikeli','office'),
('73.20','Piyasa araştırması ve kamuoyu yoklaması','Az Tehlikeli','office'),
('74.10','Uzmanlaşmış tasarım faaliyetleri','Az Tehlikeli','office'),
('74.20','Fotoğrafçılık faaliyetleri','Az Tehlikeli','office'),
('74.30','Tercüme ve tercümanlık faaliyetleri','Az Tehlikeli','office'),
('74.90','Başka yerde sınıflandırılmamış diğer mesleki, bilimsel ve teknik faaliyetler','Az Tehlikeli','office'),
('75.00','Veterinerlik hizmetleri','Az Tehlikeli','healthcare'),
('77.11','Otomobil ve hafif motorlu kara taşıtı kiralaması','Az Tehlikeli','office'),
('77.12','Kamyon, otobüs, karavan vb. kiralaması','Az Tehlikeli','office'),
('77.21','Eğlence ve spor eşyalarının kiralanması','Az Tehlikeli','office'),
('77.22','Video kasetlerinin ve disklerin kiralanması','Az Tehlikeli','office'),
('77.29','Diğer kişisel ve ev eşyalarının kiralanması','Az Tehlikeli','office'),
('77.31','Tarım makine ve ekipmanlarının kiralanması','Az Tehlikeli','office'),
('77.32','İnşaat makine ve ekipmanlarının kiralanması','Az Tehlikeli','office'),
('77.33','Büro makine ve ekipmanlarının (bilgisayarlar dahil) kiralanması','Az Tehlikeli','office'),
('77.34','Su yolu taşıma ekipmanlarının kiralanması','Az Tehlikeli','office'),
('77.35','Hava yolu taşıma ekipmanlarının kiralanması','Az Tehlikeli','office'),
('77.39','Başka yerde sınıflandırılmamış diğer makine, ekipman ve maddi malların kiralanması','Az Tehlikeli','office'),
('77.40','Fikri mülkiyet ve benzeri ürünlerin kiralanması (telif hakkı ile korunan eserler hariç)','Az Tehlikeli','office'),
('78.10','İş bulma aracı kurumlarının faaliyetleri','Az Tehlikeli','office'),
('78.20','Geçici iş gücü tedarik hizmetleri','Az Tehlikeli','office'),
('78.30','Diğer insan kaynakları temini','Az Tehlikeli','office'),
('79.11','Seyahat acentesi faaliyetleri','Az Tehlikeli','office'),
('79.12','Tur operatörlerinin faaliyetleri','Az Tehlikeli','office'),
('79.90','Diğer rezervasyon hizmet ve ilgili faaliyetler','Az Tehlikeli','office'),
('80.10','Özel güvenlik faaliyetleri','Az Tehlikeli','office'),
('80.20','Güvenlik sistemleri hizmet faaliyetleri','Az Tehlikeli','office'),
('80.30','Soruşturma faaliyetleri','Az Tehlikeli','office'),
('81.10','Kombine tesis yönetimi faaliyetleri','Az Tehlikeli','office'),
('81.21','Binaların genel temizliği','Az Tehlikeli','office'),
('81.22','Binaların ve sanayi makinelerinin diğer temizlik faaliyetleri','Az Tehlikeli','office'),
('81.29','Diğer bina ve sanayi temizliği faaliyetleri','Az Tehlikeli','office'),
('81.30','Çevre düzenleme faaliyetleri','Az Tehlikeli','office'),
('82.11','Kombine büro idari hizmet faaliyetleri','Az Tehlikeli','office'),
('82.19','Fotokopi, belge hazırlama ve diğer özelleşmiş büro destek faaliyetleri','Az Tehlikeli','office'),
('82.20','Çağrı merkezlerinin faaliyetleri','Az Tehlikeli','office'),
('82.30','Kongre, fuar ve iş organizasyonu faaliyetleri','Az Tehlikeli','office'),
('82.91','Tahsilat acenteleri ve kredi bürolarının faaliyetleri','Az Tehlikeli','office'),
('82.92','Paketleme faaliyetleri','Az Tehlikeli','office'),
('82.99','Başka yerde sınıflandırılmamış diğer iş destek hizmet faaliyetleri','Az Tehlikeli','office'),
('84.11','Genel kamu yönetimi faaliyetleri','Az Tehlikeli','office'),
('84.12','Sağlık, eğitim, kültür ve sosyal hizmetlerin yönetimi (sosyal güvenlik hariç)','Az Tehlikeli','office'),
('84.13','İşletmelerin daha etkin yürütülmesinin düzenlenmesi ve desteklenmesi','Az Tehlikeli','office'),
('84.21','Dış işleri','Az Tehlikeli','office'),
('84.22','Savunma faaliyetleri','Az Tehlikeli','office'),
('84.23','Adalet ve yargı faaliyetleri','Az Tehlikeli','office'),
('84.24','Kamu düzeni ve güvenlik faaliyetleri','Az Tehlikeli','office'),
('84.25','İtfaiye hizmetleri','Az Tehlikeli','office'),
('84.30','Zorunlu sosyal gï¿½ï¿½venlik faaliyetleri','Az Tehlikeli','office'),
('85.10','Okul öncesi eğitim','Az Tehlikeli','education'),
('85.20','İlköğretim','Az Tehlikeli','education'),
('85.31','Genel ortaöğretim','Az Tehlikeli','education'),
('85.32','Teknik ve mesleki ortaöğretim','Az Tehlikeli','education'),
('85.41','Ortaöğretim sonrası yükseköğretim dışı eğitim','Az Tehlikeli','education'),
('85.42','Yükseköğretim','Az Tehlikeli','education'),
('85.51','Spor ve eğlence amaçlı eğitim','Az Tehlikeli','education'),
('85.52','Kültürel eğitim','Az Tehlikeli','education'),
('85.53','Sürücü kursu faaliyetleri','Az Tehlikeli','education'),
('85.59','Başka yerde sınıflandırılmamış diğer eğitim','Az Tehlikeli','education'),
('85.60','Eğitimi destekleyici faaliyetler','Az Tehlikeli','education'),
('86.10','Hastane faaliyetleri','Az Tehlikeli','healthcare'),
('86.21','Genel sağlık hizmetleri','Az Tehlikeli','healthcare'),
('86.22','Uzman sağlık hizmetleri','Az Tehlikeli','healthcare'),
('86.23','Dişçilik hizmetleri','Az Tehlikeli','healthcare'),
('86.90','Diğer insan sağlığı hizmetleri','Az Tehlikeli','healthcare'),
('87.10','Hemşirelik bakım tesislerinin faaliyetleri','Az Tehlikeli','healthcare'),
('87.20','Zihinsel özürlüler, ruh sağlığı ve madde bağımlılarının yatılı olarak bakımı faaliyetleri','Az Tehlikeli','healthcare'),
('87.30','Yaşlıların ve bedensel özürlülerin yatılı olarak bakımı faaliyetleri','Az Tehlikeli','healthcare'),
('87.90','Diğer yatılı bakım faaliyetleri','Az Tehlikeli','healthcare'),
('88.10','Yaşlıların ve bedensel özürlülerin barınacak yer sağlanmaksızın verilen sosyal hizmetleri','Az Tehlikeli','healthcare'),
('88.91','Çocuk gündüz bakım faaliyetleri','Az Tehlikeli','healthcare'),
('88.99','Başka yerde sınıflandırılmamış barınacak yer sağlanmaksızın verilen diğer sosyal hizmetler','Az Tehlikeli','healthcare'),
('90.01','Gösteri sanatları','Az Tehlikeli','office'),
('90.02','Gösteri sanatlarını destekleyici faaliyetler','Az Tehlikeli','office'),
('90.03','Sanatsal yaratma faaliyetleri','Az Tehlikeli','office'),
('90.04','Sanat tesislerinin işletilmesi','Az Tehlikeli','office'),
('91.01','Kütüphane ve arşiv faaliyetleri','Az Tehlikeli','office'),
('91.02','Müze faaliyetleri','Az Tehlikeli','office'),
('91.03','Tarihi alanlar ve binalar ile benzeri turistik yerlerin işletilmesi','Az Tehlikeli','office'),
('91.04','Botanik ve hayvanat bahçeleri ile tabiat koruma faaliyetleri','Az Tehlikeli','office'),
('92.00','Kumar ve bahis faaliyetleri','Az Tehlikeli','office'),
('93.11','Spor tesislerinin işletilmesi','Az Tehlikeli','office'),
('93.12','Spor kulüplerinin faaliyetleri','Az Tehlikeli','office'),
('93.13','Fitness (sağlıklı yaşam) tesislerinin faaliyetleri','Az Tehlikeli','office'),
('93.19','Diğer spor faaliyetleri','Az Tehlikeli','office'),
('93.21','Eğlence ve tema parkları faaliyetleri','Az Tehlikeli','office'),
('93.29','Diğer eğlence ve dinlence faaliyetleri','Az Tehlikeli','office'),
('94.11','İş, işveren ve mesleki kuruluşların faaliyetleri','Az Tehlikeli','office'),
('94.12','Mesleki kuruluşların faaliyetleri','Az Tehlikeli','office'),
('94.20','İşçi sendikalarının faaliyetleri','Az Tehlikeli','office'),
('94.91','Dini kuruluşların faaliyetleri','Az Tehlikeli','office'),
('94.92','Siyasi kuruluşların faaliyetleri','Az Tehlikeli','office'),
('94.99','Başka yerde sınıflandırılmamış diğer üye olunan kuruluşların faaliyetleri','Az Tehlikeli','office'),
('95.11','Bilgisayar ve çevre birimlerinin onarımı','Az Tehlikeli','office'),
('95.12','İletişim ekipmanlarının onarımı','Az Tehlikeli','office'),
('95.21','Tüketici elektroniği ürünlerinin onarımı','Az Tehlikeli','office'),
('95.22','Evde kullanılan cihazlar ile ev ve bahçe eşyalarının onarımı','Az Tehlikeli','office'),
('95.23','Ayakkabı ve deri eşyaların onarımı','Az Tehlikeli','office'),
('95.24','Mobilya ve ev döşemelerinin onarımı','Az Tehlikeli','office'),
('95.25','Saat ve mücevherat onarımı','Az Tehlikeli','office'),
('95.29','Diğer kişisel eşyaların ve ev eşyalarının onarımı','Az Tehlikeli','office'),
('96.01','Tekstil ve kürk ürünlerinin yıkanması ve (kuru) temizlenmesi','Az Tehlikeli','office'),
('96.02','Kuaförlük ve güzellikle ilgili diğer hizmetler','Az Tehlikeli','office'),
('96.03','Cenaze işleri ve ilgili hizmetler','Az Tehlikeli','office'),
('96.04','Fiziksel rahatlama sağlayan hizmetler','Az Tehlikeli','office'),
('96.09','Başka yerde sınıflandırılmamış diğer kişisel hizmet faaliyetleri','Az Tehlikeli','office'),
('97.00','Ev içi çalışan personelin işverenleri olarak hane halklarının faaliyetleri','Az Tehlikeli','office'),
('98.10','Hane halkları tarafından kendi kullanımlarına yönelik olarak ayrım yapılmamış mal üretim faaliyetleri','Az Tehlikeli','office'),
('98.20','Hane halkları tarafından kendi kullanımlarına yönelik olarak ayrım yapılmamış hizmet üretim faaliyetleri','Az Tehlikeli','office'),
('99.00','Uluslararası örgütler ve temsilciliklerinin faaliyetleri','Az Tehlikeli','office')
ON CONFLICT (nace_code) DO NOTHING;

