// src/lib/constants/extension.ts

export const ISGVIZYON_CHROME_EXTENSION_URL =
  "https://chromewebstore.google.com/detail/ombgdbjkinmfbkpenjihlakgdppkcdbj";

export const ISGVIZYON_CHROME_EXTENSION_ID = "ombgdbjkinmfbkpenjihlakgdppkcdbj";

export const ISGVIZYON_EXTENSION_STATUS_MESSAGE = "ISGVIZYON_EXTENSION_STATUS";

export const ISGVIZYON_MULTI_ASSIGNMENT_PREVIEW = "ISGVIZYON_MULTI_ASSIGNMENT_PREVIEW";
export const ISGVIZYON_MULTI_ASSIGNMENT_APPLY = "ISGVIZYON_MULTI_ASSIGNMENT_APPLY";
export const ISGVIZYON_EXCESS_DURATION_PREVIEW = "ISGVIZYON_EXCESS_DURATION_PREVIEW";
export const ISGVIZYON_EXCESS_DURATION_APPLY = "ISGVIZYON_EXCESS_DURATION_APPLY";
export const ISGVIZYON_VALIDATE_ASSIGNMENT_SURFACE = "ISGVIZYON_VALIDATE_ASSIGNMENT_SURFACE";
export const ISGVIZYON_VALIDATE_DURATION_SURFACE = "ISGVIZYON_VALIDATE_DURATION_SURFACE";

// TODO Sprint 5: Gerçek İSG-KATİP submit işlemi kullanıcı onayı ve güvenli extension handler ile açılacaktır.
