/* AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
 * Generated by scripts/generate-public-symbols.mjs
 */

export type GeneratedPublicSymbolCategory =
  | "custom"
  | "emergency"
  | "fire"
  | "mandatory"
  | "warning"
  | "prohibition"
  | "direction";

export interface GeneratedPublicSymbol {
  id: string;
  label: string;
  category: GeneratedPublicSymbolCategory;
  color: string;
  shortCode: string;
  svgUrl?: string;
  imageSrc?: string;
}

export const PUBLIC_SYMBOLS = [
  {
    "id": "elektrik-tehlike",
    "label": "elektrik-tehlike",
    "category": "warning",
    "color": "#f59e0b",
    "shortCode": "W012",
    "svgUrl": "/symbols/elektrik-tehlike.svg"
  },
  {
    "id": "iso-7010-e001-new",
    "label": "Acil çıkış - sol yön",
    "category": "emergency",
    "color": "#009966",
    "shortCode": "E001",
    "svgUrl": "/symbols/ISO_7010_E001_new.svg"
  },
  {
    "id": "iso-7010-e002-plus-arrow-2",
    "label": "Acil çıkış - sağ yön",
    "category": "emergency",
    "color": "#009966",
    "shortCode": "E002",
    "svgUrl": "/symbols/ISO_7010_E002_+_arrow_2.svg"
  },
  {
    "id": "iso-7010-e004",
    "label": "Acil telefon",
    "category": "emergency",
    "color": "#009966",
    "shortCode": "E004",
    "svgUrl": "/symbols/ISO_7010_E004.svg"
  },
  {
    "id": "iso-7010-e007",
    "label": "Toplanma noktası",
    "category": "emergency",
    "color": "#009966",
    "shortCode": "E007",
    "svgUrl": "/symbols/ISO_7010_E007.svg"
  },
  {
    "id": "iso-7010-e016",
    "label": "Kaçış merdivenli acil pencere",
    "category": "emergency",
    "color": "#009966",
    "shortCode": "E016",
    "svgUrl": "/symbols/ISO_7010_E016.svg"
  },
  {
    "id": "iso-7010-e026",
    "label": "Yürüme engelli kişiler için acil çıkış",
    "category": "emergency",
    "color": "#009966",
    "shortCode": "E026",
    "svgUrl": "/symbols/ISO_7010_E026.svg"
  },
  {
    "id": "iso-7010-e053",
    "label": "Tahliye sandalyesi",
    "category": "emergency",
    "color": "#009966",
    "shortCode": "E053",
    "svgUrl": "/symbols/ISO_7010_E053.svg"
  },
  {
    "id": "iso-7010-f001-r2",
    "label": "Yangın söndürücü",
    "category": "fire",
    "color": "#dc2626",
    "shortCode": "F001",
    "svgUrl": "/symbols/ISO_7010_F001-r2.svg"
  },
  {
    "id": "iso-7010-f002",
    "label": "Yangın hortum makarası",
    "category": "fire",
    "color": "#dc2626",
    "shortCode": "F002",
    "svgUrl": "/symbols/ISO_7010_F002.svg"
  },
  {
    "id": "iso-7010-f003",
    "label": "Yangın merdiveni",
    "category": "fire",
    "color": "#dc2626",
    "shortCode": "F003",
    "svgUrl": "/symbols/ISO_7010_F003.svg"
  },
  {
    "id": "iso-7010-f005",
    "label": "Yangın alarm butonu",
    "category": "fire",
    "color": "#dc2626",
    "shortCode": "F005",
    "svgUrl": "/symbols/ISO_7010_F005.svg"
  },
  {
    "id": "iso-7010-f006",
    "label": "Yangın acil telefonu",
    "category": "fire",
    "color": "#dc2626",
    "shortCode": "F006",
    "svgUrl": "/symbols/ISO_7010_F006.svg"
  },
  {
    "id": "iso-7010-f007",
    "label": "Yangın kapısı",
    "category": "fire",
    "color": "#dc2626",
    "shortCode": "F007",
    "svgUrl": "/symbols/ISO_7010_F007.svg"
  },
  {
    "id": "iso-7010-f016",
    "label": "Yangın battaniyesi",
    "category": "fire",
    "color": "#dc2626",
    "shortCode": "F016",
    "svgUrl": "/symbols/ISO_7010_F016.svg"
  },
  {
    "id": "iso-7010-f019",
    "label": "Bağlantısız yangın hortumu",
    "category": "fire",
    "color": "#dc2626",
    "shortCode": "F019",
    "svgUrl": "/symbols/ISO_7010_F019.svg"
  },
  {
    "id": "iso-7010-fire-protection-arrow-1",
    "label": "Yangın ekipmanı yön oku 1",
    "category": "direction",
    "color": "#009966",
    "shortCode": "F→",
    "svgUrl": "/symbols/ISO_7010_Fire_protection_arrow_1.svg"
  },
  {
    "id": "iso-7010-fire-protection-arrow-2",
    "label": "Yangın ekipmanı yön oku 2",
    "category": "direction",
    "color": "#009966",
    "shortCode": "F→",
    "svgUrl": "/symbols/ISO_7010_Fire_protection_arrow_2.svg"
  },
  {
    "id": "iso-7010-m001",
    "label": "Genel emredici işaret",
    "category": "mandatory",
    "color": "#2563eb",
    "shortCode": "M001",
    "svgUrl": "/symbols/ISO_7010_M001.svg"
  },
  {
    "id": "iso-7010-m002",
    "label": "Talimat kitabını / kılavuzu oku",
    "category": "mandatory",
    "color": "#2563eb",
    "shortCode": "M002",
    "svgUrl": "/symbols/ISO_7010_M002.svg"
  },
  {
    "id": "iso-7010-m003",
    "label": "Kulak koruyucu kullan",
    "category": "mandatory",
    "color": "#2563eb",
    "shortCode": "M003",
    "svgUrl": "/symbols/ISO_7010_M003.svg"
  },
  {
    "id": "iso-7010-m004",
    "label": "Göz koruyucu kullan",
    "category": "mandatory",
    "color": "#2563eb",
    "shortCode": "M004",
    "svgUrl": "/symbols/ISO_7010_M004.svg"
  },
  {
    "id": "iso-7010-m005",
    "label": "Topraklama bağlantısı yap",
    "category": "mandatory",
    "color": "#2563eb",
    "shortCode": "M005",
    "svgUrl": "/symbols/ISO_7010_M005.svg"
  },
  {
    "id": "iso-7010-m008",
    "label": "İş güvenliği ayakkabısı kullan",
    "category": "mandatory",
    "color": "#2563eb",
    "shortCode": "M008",
    "svgUrl": "/symbols/ISO_7010_M008.svg"
  },
  {
    "id": "iso-7010-m009",
    "label": "Koruyucu eldiven kullan",
    "category": "mandatory",
    "color": "#2563eb",
    "shortCode": "M009",
    "svgUrl": "/symbols/ISO_7010_M009.svg"
  },
  {
    "id": "iso-7010-m010",
    "label": "Koruyucu kıyafet kullan",
    "category": "mandatory",
    "color": "#2563eb",
    "shortCode": "M010",
    "svgUrl": "/symbols/ISO_7010_M010.svg"
  },
  {
    "id": "iso-7010-m014",
    "label": "Baret kullan",
    "category": "mandatory",
    "color": "#2563eb",
    "shortCode": "M014",
    "svgUrl": "/symbols/ISO_7010_M014.svg"
  },
  {
    "id": "iso-7010-m016",
    "label": "Maske kullan",
    "category": "mandatory",
    "color": "#2563eb",
    "shortCode": "M016",
    "svgUrl": "/symbols/ISO_7010_M016.svg"
  },
  {
    "id": "iso-7010-m018",
    "label": "Emniyet kemeri / güvenlik halatı kullan",
    "category": "mandatory",
    "color": "#2563eb",
    "shortCode": "M018",
    "svgUrl": "/symbols/ISO_7010_M018.svg"
  },
  {
    "id": "iso-7010-m020-1",
    "label": "Emniyet kemeri tak",
    "category": "mandatory",
    "color": "#2563eb",
    "shortCode": "M020",
    "svgUrl": "/symbols/ISO_7010_M020 (1).svg"
  },
  {
    "id": "iso-7010-m020",
    "label": "Emniyet kemeri tak",
    "category": "mandatory",
    "color": "#2563eb",
    "shortCode": "M020",
    "svgUrl": "/symbols/ISO_7010_M020.svg"
  },
  {
    "id": "iso-7010-m046-mandatory-secure-gas-cylinders",
    "label": "Gaz tüpünü sabitle",
    "category": "mandatory",
    "color": "#2563eb",
    "shortCode": "M046",
    "svgUrl": "/symbols/ISO_7010_M046;_mandatory;_secure_gas_cylinders.svg"
  },
  {
    "id": "iso-7010-p001",
    "label": "Genel yasak",
    "category": "prohibition",
    "color": "#dc2626",
    "shortCode": "P001",
    "svgUrl": "/symbols/ISO_7010_P001.svg"
  },
  {
    "id": "iso-7010-p004",
    "label": "Geçiş yok / giriş yasak",
    "category": "prohibition",
    "color": "#dc2626",
    "shortCode": "P004",
    "svgUrl": "/symbols/ISO_7010_P004.svg"
  },
  {
    "id": "iso-7010-p005",
    "label": "İçilmez su",
    "category": "prohibition",
    "color": "#dc2626",
    "shortCode": "P005",
    "svgUrl": "/symbols/ISO_7010_P005.svg"
  },
  {
    "id": "iso-7010-p010",
    "label": "Dokunma",
    "category": "prohibition",
    "color": "#dc2626",
    "shortCode": "P010",
    "svgUrl": "/symbols/ISO_7010_P010.svg"
  },
  {
    "id": "iso-7010-p012-1",
    "label": "Ağır yük yasaktır",
    "category": "prohibition",
    "color": "#dc2626",
    "shortCode": "P012",
    "svgUrl": "/symbols/ISO_7010_P012 (1).svg"
  },
  {
    "id": "iso-7010-p012",
    "label": "Ağır yük yasaktır",
    "category": "prohibition",
    "color": "#dc2626",
    "shortCode": "P012",
    "svgUrl": "/symbols/ISO_7010_P012.svg"
  },
  {
    "id": "iso-7010-safe-condition-arrow-1",
    "label": "Güvenli yön oku 1",
    "category": "direction",
    "color": "#009966",
    "shortCode": "E→",
    "svgUrl": "/symbols/ISO_7010_Safe_condition_arrow_1.svg"
  },
  {
    "id": "iso-7010-safe-condition-arrow-2",
    "label": "Güvenli yön oku 2",
    "category": "direction",
    "color": "#009966",
    "shortCode": "E→",
    "svgUrl": "/symbols/ISO_7010_Safe_condition_arrow_2.svg"
  },
  {
    "id": "iso-7010-w001-svg",
    "label": "Genel uyarı",
    "category": "warning",
    "color": "#f59e0b",
    "shortCode": "W001",
    "imageSrc": "/symbols/ISO_7010_W001.svg.png"
  },
  {
    "id": "iso-7010-w003-svg",
    "label": "Radyoaktif madde / iyonlaştırıcı radyasyon",
    "category": "warning",
    "color": "#f59e0b",
    "shortCode": "W003",
    "imageSrc": "/symbols/ISO_7010_W003.svg.png"
  },
  {
    "id": "iso-7010-w008",
    "label": "Düşme tehlikesi",
    "category": "warning",
    "color": "#f59e0b",
    "shortCode": "W008",
    "svgUrl": "/symbols/ISO_7010_W008.svg"
  },
  {
    "id": "iso-7010-w012-svg",
    "label": "Elektrik tehlikesi",
    "category": "warning",
    "color": "#f59e0b",
    "shortCode": "W012",
    "imageSrc": "/symbols/ISO_7010_W012.svg.png"
  },
  {
    "id": "iso-7010-w021",
    "label": "Yanıcı madde",
    "category": "warning",
    "color": "#f59e0b",
    "shortCode": "W021",
    "svgUrl": "/symbols/ISO_7010_W021.svg"
  },
  {
    "id": "iso-7010-w070-svg",
    "label": "Basamak / seviye farkı tehlikesi",
    "category": "warning",
    "color": "#f59e0b",
    "shortCode": "W070",
    "imageSrc": "/symbols/ISO_7010_W070.svg.png"
  }
] satisfies GeneratedPublicSymbol[];
